線性回歸訓練

In [23]:
import numpy as np
from sklearn import linear_model

# 宣告資料
X = [[1],[2],[3],[4]]
y = [2, 4, 6, 8]

# 建立及訓練模型
regr = linear_model.LinearRegression()
regr.fit(X, y)

# 看看訓練出來的係數
print('Coefficients: ', regr.coef_ )
print('Residues: ', regr.residues_ )

# 用模型來預測一筆新的資料看看
regr.predict(5)
# >>> array([ 10.])

Coefficients:  [ 2.]
Residues:  1.54777103026e-33


/usr/local/lib/python3.6/site-packages/sklearn/utils/deprecation.py:70: DeprecationWarning: Function residues_ is deprecated; ``residues_`` is deprecated and will be removed in 0.19
  warnings.warn(msg, category=DeprecationWarning)


array([ 10.])

邏輯回歸訓練

In [24]:
import numpy as np
from sklearn import linear_model

# 宣告資料
X = [[1],[2],[3],[4]]
y = [1, 1, 0, 0]

# 建立及訓練模型
regr = linear_model.LogisticRegression()
regr.fit(X, y)

print('Coefficients: ', regr.coef_ )
print('intercept: ', regr.intercept_ )
print('n_iter: ', regr.n_iter_ )
 

# 用模型來預測一筆新的資料看看
regr.predict(0)
# >>> array([ 0.])


Coefficients:  [[-0.38626051]]
intercept:  [ 0.46757953]
n_iter:  [3]


array([1])